/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AIChatDialog: typeof import('./src/components/AIChatDialog.vue')['default']
    AppShell: typeof import('./src/components/AppShell.vue')['default']
    ButtonModule: typeof import('./src/components/modules/ButtonModule.vue')['default']
    ButtonProperty: typeof import('./src/components/property-editors/ButtonProperty.vue')['default']
    ContainerModule: typeof import('./src/components/modules/ContainerModule.vue')['default']
    ContainerProperty: typeof import('./src/components/property-editors/ContainerProperty.vue')['default']
    DividerModule: typeof import('./src/components/modules/DividerModule.vue')['default']
    DividerProperty: typeof import('./src/components/property-editors/DividerProperty.vue')['default']
    EditorCanvas: typeof import('./src/components/EditorCanvas.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    FooterModule: typeof import('./src/components/modules/FooterModule.vue')['default']
    FooterProperty: typeof import('./src/components/property-editors/FooterProperty.vue')['default']
    HeaderModule: typeof import('./src/components/modules/HeaderModule.vue')['default']
    HeaderProperty: typeof import('./src/components/property-editors/HeaderProperty.vue')['default']
    HeadingModule: typeof import('./src/components/modules/HeadingModule.vue')['default']
    HeadingProperty: typeof import('./src/components/property-editors/HeadingProperty.vue')['default']
    ImageModule: typeof import('./src/components/modules/ImageModule.vue')['default']
    ImageProperty: typeof import('./src/components/property-editors/ImageProperty.vue')['default']
    MarkdownModule: typeof import('./src/components/modules/MarkdownModule.vue')['default']
    MarkdownProperty: typeof import('./src/components/property-editors/MarkdownProperty.vue')['default']
    ModuleItem: typeof import('./src/components/ModuleItem.vue')['default']
    ModuleLibrary: typeof import('./src/components/ModuleLibrary.vue')['default']
    ModuleRenderer: typeof import('./src/components/ModuleRenderer.vue')['default']
    PreviewCanvas: typeof import('./src/components/PreviewCanvas.vue')['default']
    PropertyPanel: typeof import('./src/components/PropertyPanel.vue')['default']
    QuoteModule: typeof import('./src/components/modules/QuoteModule.vue')['default']
    QuoteProperty: typeof import('./src/components/property-editors/QuoteProperty.vue')['default']
    RichTextEditor: typeof import('./src/components/RichTextEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TextModule: typeof import('./src/components/modules/TextModule.vue')['default']
    TextProperty: typeof import('./src/components/property-editors/TextProperty.vue')['default']
    TocModule: typeof import('./src/components/modules/TocModule.vue')['default']
    TocProperty: typeof import('./src/components/property-editors/TocProperty.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
